using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RotMG_Lib.Network
{
    public enum PacketID : byte
    {
        Failure = 0,
	    Create_Success = 53,
	    Create = 86,
	    PlayerShoot = 56,
	    Move = 34,
	    PlayerText = 9,
	    Text = 60,
	    Shoot2 = 80,
	    Damage = 74,
	    Update = 5,
	    UpdateAck = 42,
	    Notification = 38,
	    New_Tick = 92,
	    InvSwap = 66,
	    UseItem = 67,
	    Show_Effect = 59,
	    Hello = 88,
	    Goto = 87,
	    InvDrop = 57,
	    InvResult = 8,
	    Reconnect = 25,
	    Ping = 44,
	    Pong = 1,
	    MapInfo = 75,
	    Load = 17,
	    Pic = 91,
	    SetCondition = 61,
	    Teleport = 68,
	    UsePortal = 55,
	    Death = 11,
	    Buy = 24,
	    BuyResult = 13,
	    AOE = 33,
	    GroundDamage = 28,
	    PlayerHit = 81,
	    EnemyHit = 14,
	    AOEAck = 63,
	    ShootAck = 47,
	    OtherHit = 79,
	    SquareHit = 77,
	    GotoAck = 78,
	    EditAccountList = 90,
	    AccountList = 82,
	    QuestObjID = 30,
	    ChooseName = 4,
	    NameResult = 58,
	    CreateGuild = 23,
	    CreateGuildResult = 36,
	    GuildRemove = 84,
	    GuildInvite = 40,
	    AllyShoot = 7,
	    Shoot = 6,
	    RequestTrade = 22,
	    TradeRequested = 21,
	    TradeStart = 83,
	    ChangeTrade = 41,
	    TradeChanged = 64,
	    AcceptTrade = 62,
	    CancelTrade = 51,
	    TradeDone = 49,
	    TradeAccepted = 94,
	    ClientStat = 65,
	    CheckCredits = 85,
	    Escape = 31,
	    File = 37,
	    InviteToGuild = 45,
	    JoinGuild = 26,
	    ChangeGuildRank = 69,
	    PlaySound = 10,
	    Global_Notification = 27,
	    Reskin = 50,
	    __1o_ = 48,
	    __H = 93,
	    __1qM = 52,
	    __14q = 12,
	    __yS = 15,
	    __1oV = 19,
	    __06E = 3,
	    __1O6 = 76,
	    Enter_Arena = 35,
	    __YE = 46,
	    __Q8 = 18,
	    __Tu = 89,
	    __1A8 = 16,
	    __5K = 39,
	    __qv = 20
    }
}
