using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RotMG_Lib
{
    [Flags]
    public enum ConditionEffects
    {
        Dead = 1 << 0,
        Quiet = 1 << 1,
        Weak = 1 << 2,
        Slowed = 1 << 3,
        Sick = 1 << 4,
        Dazed = 1 << 5,
        Stunned = 1 << 6,
        Blind = 1 << 7,
        Hallucinating = 1 << 8,
        Drunk = 1 << 9,
        Confused = 1 << 10,
        StunImmume = 1 << 11,
        Invisible = 1 << 12,
        Paralyzed = 1 << 13,
        Speedy = 1 << 14,
        Bleeding = 1 << 15,
        NotUsed = 1 << 16,
        Healing = 1 << 17,
        Damaging = 1 << 18,
        Berserk = 1 << 19,
        Paused = 1 << 20,
        Stasis = 1 << 21,
        StasisImmune = 1 << 22,
        Invincible = 1 << 23,
        Invulnerable = 1 << 24,
        Armored = 1 << 25,
        ArmorBroken = 1 << 26
    }

    public enum ConditionEffectIndex
    {
        Dead = 0,
        Quiet = 1,
        Weak = 2,
        Slowed = 3,
        Sick = 4,
        Dazed = 5,
        Stunned = 6,
        Blind = 7,
        Hallucinating = 8,
        Drunk = 9,
        Confused = 10,
        StunImmume = 11,
        Invisible = 12,
        Paralyzed = 13,
        Speedy = 14,
        Bleeding = 15,
        NotUsed = 16,
        Healing = 17,
        Damaging = 18,
        Berserk = 19,
        Paused = 20,
        Stasis = 21,
        StasisImmune = 22,
        Invincible = 23,
        Invulnerable = 24,
        Armored = 25,
        ArmorBroken = 26,
        Hexed = 27
    }

    public enum StatTypes : byte
    {
        MAXIMUM_HP = 0,
        HP = 1,
        SIZE = 2,
        MAXIMUM_MP = 3,
        MP = 4,
        EXPERIENCE_GOAL = 5,
        EXPERIENCE = 6,
        LEVEL = 7,
        INVENTORY_0 = 8,
        INVENTORY_1 = 9,
        INVENTORY_2 = 10,
        INVENTORY_3 = 11,
        INVENTORY_4 = 12,
        INVENTORY_5 = 13,
        INVENTORY_6 = 14,
        INVENTORY_7 = 15,
        INVENTORY_8 = 16,
        INVENTORY_9 = 17,
        INVENTORY_10 = 18,
        INVENTORY_11 = 19,
        ATTACK = 20,
        DEFENCE = 21,
        SPEED = 22,
        VITALITY = 26,
        WISDOM = 27,
        DEXTERITY = 28,
        EFFECTS = 29,
        STARS = 30,
        NAME = 31,
        TEXTURE_1 = 32,
        TEXTURE_2 = 33,
        MERCHANT_MERCHANDISE_TYPE = 34,
        CREDITS = 35,
        SELLABLE_PRICE = 36,
        PORTAL_USABLE = 37,
        ACCOUNT_ID = 38,
        CURRENT_FAME = 39,
        SELLABLE_PRICE_CURRENCY = 40,
        OBJECT_CONNECTION = 41,
        MERCHANT_REMAINING_COUNT = 42,
        MERCHANT_REMAINING_MINUTE = 43,
        MERCHANT_DISCOUNT = 44,
        SELLABLE_RANK_REQUIREMENT = 45,
        HP_BOOST = 46,
        MP_BOOST = 47,
        ATTACK_BONUS = 48,
        DEFENSE_BONUS = 49,
        SPEED_BONUS = 50,
        VITALITY_BONUS = 51,
        WISDOM_BONUS = 52,
        DEXTERITY_BONUS = 53,
        OWNER_ACCOUNT_ID = 54,
        NAME_CHANGER_STAR = 55,
        NAME_CHOSEN = 56,
        FAME = 57,
        FAME_GOAL = 58,
        GLOWING = 59,
        SINK_OFFSET = 60,
        ALT_TEXTURE_INDEX = 61,
        GUILD = 62,
        GUILD_RANK = 63,
        OXYGEN_BAR = 64,
        _uq = 65,
        _Jw = 66,
        _Ks = 67,
        _0RR = 68,
        _Dz = 69,
        _Mp = 70,
        BACKPACK_0_STAT = 71,
        BACKPACK_1_STAT = 72,
        BACKPACK_2_STAT = 73,
        BACKPACK_3_STAT = 74,
        BACKPACK_4_STAT = 75,
        BACKPACK_5_STAT = 76,
        BACKPACK_6_STAT = 77,
        BACKPACK_7_STAT = 78,
        HAS_BACKPACK = 79,
        _1Rn = 80,
        _BB = 81,
        UNKNOWN_TEXT_2 = 82,
        _0EQ = 83,
        _Zr = 84,
        _1AC = 85,
        _0PG = 86,
        _02a = 87,
        _1No = 88,
        _Qh = 89,
        _Iy = 90,
        _9N = 91,
        _0Er = 92,
        _HJ = 93,
        _yg = 94,
        _lg = 95
    }
}
